In [1]:
#Importing the Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
#Importing the Datasets
df=pd.read_csv('500_Person_Gender_Height_Weight_Index.csv')
df

Gender  Height  Weight  Index
0      Male     174      96      4
1      Male     189      87      2
2    Female     185     110      4
3    Female     195     104      3
4      Male     149      61      3
..      ...     ...     ...    ...
495  Female     150     153      5
496  Female     184     121      4
497  Female     141     136      5
498    Male     150      95      5
499    Male     173     131      5

[500 rows x 4 columns]

In [3]:
#Checking for Null Values
df.isnull().sum()

Gender    0
Height    0
Weight    0
Index     0
dtype: int64

In [4]:
df['Index'].value_counts()

5    198
4    130
2     69
3     68
1     22
0     13
Name: Index, dtype: int64

In [5]:
df["Gender"].value_counts()

Female    255
Male      245
Name: Gender, dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le=LabelEncoder()

In [8]:
df['Gender']=le.fit_transform(df['Gender'])

In [9]:
df

Gender  Height  Weight  Index
0         1     174      96      4
1         1     189      87      2
2         0     185     110      4
3         0     195     104      3
4         1     149      61      3
..      ...     ...     ...    ...
495       0     150     153      5
496       0     184     121      4
497       0     141     136      5
498       1     150      95      5
499       1     173     131      5

[500 rows x 4 columns]

In [10]:
df["Gender"].value_counts()

0    255
1    245
Name: Gender, dtype: int64

In [11]:
#Model Selection
from sklearn.model_selection import train_test_split

In [12]:
X=df.iloc[:,:-1].values

In [13]:
X

array([[  1, 174,  96],
       [  1, 189,  87],
       [  0, 185, 110],
       ...,
       [  0, 141, 136],
       [  1, 150,  95],
       [  1, 173, 131]], dtype=int64)

In [14]:
y=df.iloc[:,-1].values

In [15]:
y

array([4, 2, 4, 3, 3, 3, 5, 5, 3, 4, 2, 4, 3, 2, 2, 5, 5, 5, 5, 5, 5, 5,
       4, 5, 2, 3, 3, 1, 5, 5, 5, 1, 1, 5, 5, 4, 3, 4, 5, 2, 4, 5, 2, 5,
       4, 2, 4, 4, 3, 5, 5, 1, 5, 4, 4, 3, 4, 5, 3, 5, 0, 5, 0, 2, 5, 5,
       4, 2, 4, 4, 2, 4, 5, 2, 3, 4, 4, 4, 4, 0, 3, 5, 3, 4, 5, 0, 5, 5,
       5, 5, 5, 3, 3, 2, 4, 5, 4, 5, 1, 0, 4, 5, 5, 4, 4, 4, 5, 5, 4, 3,
       4, 5, 4, 2, 4, 3, 2, 5, 5, 5, 4, 4, 4, 5, 5, 4, 4, 4, 5, 2, 5, 2,
       5, 4, 5, 5, 5, 3, 5, 5, 2, 4, 5, 5, 5, 4, 3, 5, 3, 3, 0, 3, 3, 5,
       5, 4, 3, 5, 3, 4, 2, 2, 3, 5, 4, 2, 4, 5, 3, 2, 4, 5, 5, 4, 4, 4,
       4, 3, 5, 3, 3, 4, 4, 2, 3, 3, 5, 3, 5, 4, 5, 5, 4, 5, 5, 5, 4, 4,
       5, 5, 1, 3, 4, 4, 5, 4, 5, 4, 3, 4, 4, 5, 5, 5, 0, 5, 5, 5, 5, 5,
       2, 5, 4, 5, 0, 5, 3, 4, 5, 5, 4, 2, 3, 3, 4, 3, 5, 5, 2, 5, 3, 2,
       1, 5, 0, 5, 3, 5, 3, 4, 3, 5, 5, 5, 5, 2, 4, 5, 5, 4, 5, 5, 5, 2,
       4, 5, 5, 5, 5, 1, 5, 5, 4, 0, 3, 3, 4, 2, 3, 1, 1, 5, 5, 4, 4, 4,
       4, 5, 2, 5, 4, 3, 3, 4, 5, 5, 2, 4, 3, 4, 5,

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [17]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression

In [18]:
lr=LogisticRegression()

In [19]:
lr.fit(X_train,y_train)

C:\Users\srini\AppData\Roaming\Python\Python38\site-packages\sklearn\linear_model\_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [20]:
lr.score(X_test,y_test)

0.78

In [21]:
#Training on Naive-Bayes
from sklearn.naive_bayes import GaussianNB

In [22]:
gnb=GaussianNB()

In [23]:
gnb.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [24]:
gnb.score(X_test,y_test)

0.76

In [25]:
#K-Nearest Neighbours
from sklearn.neighbors import KNeighborsClassifier

In [26]:
knc=KNeighborsClassifier(n_neighbors=5)

In [27]:
knc.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [28]:
knc.score(X_test,y_test)

0.92

In [29]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier

In [30]:
dtc=DecisionTreeClassifier()

In [31]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [32]:
dtc.score(X_test,y_test)

0.92

In [33]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

In [34]:
rfc=RandomForestClassifier(criterion='entropy')

In [35]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [36]:
rfc.score(X_test,y_test)

0.87

In [37]:
#Gradient Boosting
from sklearn.ensemble import GradientBoostingClassifier

In [38]:
gbc=GradientBoostingClassifier()

In [39]:
gbc.fit(X_train,y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [40]:
gbc.score(X_test,y_test)

0.9

The Best Fit Algorithm for this Dataset is KNeighbours Classifier
--

In [41]:
y_predict=knc.predict(X_test)

In [42]:
#Predicting the test result
print(np.concatenate((y_predict.reshape(len(y_predict),1), y_test.reshape(len(y_test),1)),1))

[[5 4]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [5 5]
 [5 5]
 [5 5]
 [4 4]
 [5 5]
 [4 4]
 [5 5]
 [2 2]
 [5 5]
 [5 5]
 [3 3]
 [5 5]
 [5 5]
 [3 3]
 [5 5]
 [2 2]
 [5 5]
 [1 1]
 [4 4]
 [4 4]
 [5 5]
 [5 5]
 [5 5]
 [5 5]
 [2 2]
 [4 4]
 [5 5]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [5 5]
 [2 2]
 [4 4]
 [2 2]
 [5 5]
 [1 2]
 [4 4]
 [3 3]
 [5 5]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 5]
 [4 4]
 [2 2]
 [1 1]
 [5 5]
 [3 3]
 [3 3]
 [5 5]
 [5 5]
 [4 4]
 [5 5]
 [5 5]
 [5 5]
 [5 4]
 [0 0]
 [2 2]
 [3 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [3 4]
 [5 5]
 [5 5]
 [5 5]
 [4 4]
 [2 2]
 [5 5]
 [5 5]
 [3 3]
 [2 2]
 [5 5]
 [4 4]
 [5 5]
 [3 3]
 [5 5]
 [4 5]
 [3 3]
 [1 1]
 [2 2]
 [5 5]
 [4 4]
 [5 5]
 [2 2]
 [5 5]
 [5 4]
 [1 1]
 [5 5]]


In [43]:
#Making Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_predict)
print(cm)
accuracy_score(y_test, y_predict)*100

[[ 1  0  0  0  0  0]
 [ 0  4  0  0  0  0]
 [ 0  1 17  0  0  0]
 [ 0  0  0  8  0  0]
 [ 0  0  0  2 25  3]
 [ 0  0  0  0  2 37]]


92.0

In [44]:
#Predicting the new result
print(knc.predict([[0,150,55]]))

[2]


In [45]:
#Save the model
import pickle as pl

In [46]:
pl.dump(knc,open('bmi_checker.pkl','wb'))